import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import LaptopIcon from "@material-ui/icons/Laptop";
export default function Home() {
  return (
    <HomeC>
      <Head>
        <title>Whatsapp | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/whatsapp.png" />
      </Head>
      <MainC>
        <img
          src="/whatsapp.jpg"
          width="330"
          height="350"
        />
        <h2>Keep your phone connected</h2>
        <div>
          <p>
            WhatsApp connects to your phone to sync messages. To reduce data
            usage, connect your phone to Wi-Fi.
          </p>
        </div>
        <HrC />
        <FotterC>
          <span>
            <LaptopIconC />
          </span>
          <span>Make calls from desktop with WhatsApp for Windows. </span>
        </FotterC>
      </MainC>
    </HomeC>
  );
}

const HomeC = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100vh;
  background: #262d31;
  padding: 0px;
  margin: -5px 0px;
  color: #a6a8ab;
`;

const MainC = styled.main`
  margin-top: -30px;
  width: 50%;
  text-align: center;
  > img {
    pointer-events: none;
    border-radius: 50%;
  }
  > h2 {
    font-size: 30px;
    font-weight: 300;
    word-spacing: 3px;
    margin: 16px 0px;
  }

  p {
    font-size: 16px;
    line-height: 1.6;
  }
`;

const HrC = styled.hr`
  margin-top: 20px;
  opacity: 0.1;
`;
const FotterC = styled.div`
  margin-top: 25px;
  display: flex;
  justify-content: center;
  align-items: center;

  > span {
    display: block;
    margin: 3px;
    font-size: 17px;
  }
`;

const LaptopIconC = styled(LaptopIcon)``;
